// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCchLt8u7D9jgRy4uG7bqljpQ_7KttsDU4',
    appId: '1:606092929326:web:7741c99513966f7048b2bf',
    messagingSenderId: '606092929326',
    projectId: 'chives-a6aaf',
    authDomain: 'chives-a6aaf.firebaseapp.com',
    storageBucket: 'chives-a6aaf.appspot.com',
    measurementId: 'G-6HVLNJBG2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmQgeJuhcplXcCRsEp9Qre7eDtMRcQJDs',
    appId: '1:606092929326:android:deb3fd63fbb1e46e48b2bf',
    messagingSenderId: '606092929326',
    projectId: 'chives-a6aaf',
    storageBucket: 'chives-a6aaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwrc1iJ9shYbOV_rLXUqROhOM5bBGHBAQ',
    appId: '1:606092929326:ios:277b34ef190cc1b348b2bf',
    messagingSenderId: '606092929326',
    projectId: 'chives-a6aaf',
    storageBucket: 'chives-a6aaf.appspot.com',
    iosClientId: '606092929326-n5k5t6mqk4pi0402pcmsfr9d6dmfu54b.apps.googleusercontent.com',
    iosBundleId: 'com.example.chives',
  );
}
